### ISSUE TITLE
nextjs compatibility status

### ISSUE THREAD

**Issue by domosedov** [kireevmp/effector-swc-plugin#10]
# My test
| Plugin version   | Next.js stable version | Status | Next.js canary version | Status |
| ---------------- | ---------------------- | ------ | ---------------------- | ------ |
| 0.2.0            | 14.1.0                 | 🔴     | 14.1.1-canary.47       | 🟢     |
| 0.2.0-swc1.3.63  | 14.1.0                 | 🟢     | 14.1.1-canary.47       | 🔴     |
| 0.2.0-swc1.3.106 | 14.1.0                 | 🔴     | 14.1.1-canary.47       | 🟢     |
| 0.2.1            | 14.1.0                 | 🔴     | 14.1.1-canary.47       | 🔴     |
| 0.2.1-swc1.3.63  | 14.1.0                 | 🟢     | 14.1.1-canary.47       | 🔴     |
| 0.2.1-swc1.3.106 | 14.1.0                 | 🔴     | 14.1.1-canary.47       | 🔴     |
| 0.2.1-swc1.4.0   | 14.1.0                 | 🔴     | 14.1.1-canary.47       | 🔴     |
| 0.2.2            | 14.1.0                 | 🔴     | 14.1.1-canary.48       | 🔴     |
| 0.2.2-swc1.3.63  | 14.1.0                 | 🟢     | 14.1.1-canary.48       | 🔴     |
| 0.2.2-swc1.3.106 | 14.1.0                 | 🔴     | 14.1.1-canary.48       | 🟢     |
| 0.2.2-swc1.4.0   | 14.1.0                 | 🔴     | 14.1.1-canary.48       | 🔴     |

**Comment by kireevmp** [comment]
Nice catch, thanks @domosedov 🙏 
Seems NextJS canary not working is caused by https://github.com/swc-project/swc/issues/8613. I'll rebuild the plugin with the fixed SWC version now.

**Comment by kireevmp** [comment]
I've published a fix in v0.2.2 with the updated SWC library. Can you check if that fixes the issue for you on `next@14.1.1-canary.47`?

**Comment by domosedov** [comment]
> I've published a fix in v0.2.2 with the updated SWC library. Can you check if that fixes the issue for you on `next@14.1.1-canary.47`?

I've updated the compatibility table

**Comment by domosedov** [comment]
swc_core update

https://github.com/vercel/next.js/pull/61976

| Plugin version   | Next.js canary version | Status |
| ---------------- | ---------------------- | ------ |
| 0.2.2            | 14.1.1-canary.54       | 🔴     |
| 0.2.2-swc1.3.63  | 14.1.1-canary.54       | 🔴     |
| 0.2.2-swc1.3.106 | 14.1.1-canary.54       | 🔴     |
| 0.2.2-swc1.4.0   | 14.1.1-canary.54       | 🔴     |

**Comment by kireevmp** [comment]
Seems this is a bug of NextJS: https://github.com/vercel/next.js/issues/62081

**Comment by Marsony** [comment]
14.1.2 works as well with ```"effector-swc-plugin": "0.3.0-swc1.3.63",```

**Comment by kireevmp** [comment]
I added an "official" compatibility table in [NextJS-specific](https://github.com/kireevmp/effector-swc-plugin/blob/master/NEXTJS.md#plugin-compatibility) doc. That table is checked with a bunch of integration tests that I run on each release, so it should be very accurate and you should refer to it

If you find an issue with incompatible Next versions, feel free to open a new issue 🙏
