### ISSUE TITLE
`domain` transform bug

### ISSUE THREAD

**Issue by domosedov** [kireevmp/effector-swc-plugin#12]
https://github.com/d3/d3-scale/blob/d6904a4bde09e16005e0ad8ca3e25b10ce54fa0d/src/ordinal.js#L21

## description
Transform array `['value1', 'value2']` to object like `{ sid: 'some sid', name: 'domain' }` 

### Reproduce
https://github.com/domosedov/swc-domain-bug

```
"next": "14.1.0",
"effector-swc-plugin": "0.2.2-swc1.3.63",
"recharts": "^2.12.1",
```

### Reproduce
https://github.com/domosedov/swc-domain-bug

<img width="1423" alt="Снимок экрана 2024-02-27 в 09 13 58" src="https://github.com/kireevmp/effector-swc-plugin/assets/42298502/92c247d4-f9b5-43c9-aeb5-9cbf26fa5e0c">
<img width="1417" alt="Снимок экрана 2024-02-27 в 09 14 31" src="https://github.com/kireevmp/effector-swc-plugin/assets/42298502/f7de2e22-0e1d-48c8-bf7d-8d22013f6437">

**Comment by domosedov** [comment]
```
"next": "14.1.0",
"effector-swc-plugin": "0.2.2-swc1.3.63",
"recharts": "^2.12.1",
```

**Comment by domosedov** [comment]
Babel plugin has same problem
<img width="1378" alt="Снимок экрана 2024-02-27 в 09 38 55" src="https://github.com/kireevmp/effector-swc-plugin/assets/42298502/e3ec4c49-287d-49c8-9e8f-2de8632aa083">
<img width="1375" alt="Снимок экрана 2024-02-27 в 09 39 04" src="https://github.com/kireevmp/effector-swc-plugin/assets/42298502/1f74aafc-ff11-474b-9369-cd9e4032d76f">

**Comment by domosedov** [comment]
Some context

For babel plugin its solve problem

https://github.com/effector/effector/blob/5352b9303f04163a35c9c1cf99cabe515341ae3b/src/babel/babel-plugin.js#L529

``` 
{
  "domainMethods": {
    "store": [],
    "event": [],
    "effect": [],
    "domain": []
  }
}
```

**Comment by kireevmp** [comment]
This now should be covered by `transformLegacyDomainMethods` option, which you can disable. Can you see if `v0.3.0` fixes this for you when using this option?
